export interface SearchResult {
    id: number;
    company: string;
    title: string;
    price: number;
    product: boolean;
    service: boolean;
    searchtags: string;
    description: string;
    image: string;
  }
  
  const Posts: SearchResult[] = [
      {
        id: 1,
        company: "ABC Electronics",
        title: "Phone Repair",
        price: 14.99,
        product: false,
        service: true,
        searchtags: "phone, repair, tech, help, service",
        description: "This is a description for Phone Repair. Lorem ipsum...",
        image: "https://i.imgur.com/n14Fh9n.jpg",
  
      },
      {
        id: 2,
        company: "ABC Electronics",
        title: "Replacement Screen",
        price: 5.99,
        product: true,
        service: false,
        searchtags: "phone, repair, tech, help, screen, replacement",
        description: "This is a description for Replacement Screen. Lorem ipsum...",
        image: "https://i.imgur.com/DYf8dOy.jpg",
      },
      {
        id: 3,
        company: "XYZ Tech",
        title: "Computer Tune-up",
        price: 29.99,
        product: false,
        service: true,
        searchtags: "computer, tune-up, tech, service",
        description: "This is a description for Computer Tune-up. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-1.jpg",
      },
      {
        id: 4,
        company: "Tech Masters",
        title: "USB Flash Drive (16GB)",
        price: 9.99,
        product: true,
        service: false,
        searchtags: "USB, flash drive, storage, tech, product",
        description: "This is a description for 16GB USB Flash Drive. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-2.jpg",
        },
        
      {
        id: 5,
        company: "Gadget Guru",
        title: "Virus Removal Service",
        price: 39.99,
        product: false,
        service: true,
        searchtags: "virus removal, computer, tech, service",
        description: "This is a description for Virus Removal Service. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-3.jpg",
      },     
      {
        id: 6,
        company: "Digital Haven",
        title: "Wireless Mouse",
        price: 14.99,
        product: true,
        service: false,
        searchtags: "wireless mouse, computer, tech, product",
        description: "This is a description for Wireless Mouse. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-4.jpg",
      },  
      {
        id: 7,
        company: "Phone Pros",
        title: "Phone Battery Replacement",
        price: 19.99,
        product: false,
        service: true,
        searchtags: "phone, battery, replacement, tech, service",
        description: "This is a description for Phone Battery Replacement. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-5.jpg",
      },  
      {
        id: 8,
        company: "Phone Pros",
        title: "Bluetooth Earbuds",
        price: 29.99,
        product: true,
        service: false,
        searchtags: "earbuds, headphones, tech, product",
        description: "This is a description for Bluetooth Earbuds. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-6.jpg",
      },
      {
        id: 9,
        company: "Gadget Galaxy",
        title: "Tablet Screen Repair",
        price: 49.99,
        product: false,
        service: true,
        searchtags: "tablet, screen repair, tech, service",
        description: "This is a description for Tablet Screen Repair. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-7.jpg",
      },
      {
        id: 10,
        company: "Gadget Galaxy",
        title: "Portable Charger (10000mAh)",
        price: 19.99,
        product: true,
        service: false,
        searchtags: "portable charger, power bank, tech, product",
        description: "This is a description for 10000mAh Portable Charger. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-8.jpg",
      },
      {
        id: 11,
        company: "PC Wizardry",
        title: "Data Recovery Service",
        price: 79.99,
        product: false,
        service: true,
        searchtags: "data recovery, computer, tech, service",
        description: "This is a description for Data Recovery Service. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-9.jpg",
      },
      {
        id: 12,
        company: "PC Wizardry",
        title: "External Hard Drive (1TB)",
        price: 59.99,
        product: true,
        service: false,
        searchtags: "external hard drive, storage, tech, product",
        description: "This is a description for 1TB External Hard Drive. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-10.jpg",
      },
      {
        id: 13,
        company: "Tech Solutions",
        title: "Laptop Keyboard Replacement",
        price: 34.99,
        product: false,
        service: true,
        searchtags: "laptop, keyboard, replacement, tech, service",
        description: "This is a description for Laptop Keyboard Replacement. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-11.jpg",
      },
      {
        id: 14,
        company: "Tech Solutions",
        title: "Bluetooth Speaker",
        price: 49.99,
        product: true,
        service: false,
        searchtags: "Bluetooth speaker, audio, tech, product",
        description: "This is a description for Bluetooth Speaker. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-12.jpg",
      },
      {
        id: 15,
        company: "Electronics Express",
        title: "Game Console Repair",
        price: 59.99,
        product: false,
        service: true,
        searchtags: "game console, repair, gaming, tech, service",
        description: "This is a description for Game Console Repair. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-13.jpg",
      },
      {
        id: 16,
        company: "Electronics Express",
        title: "Smartphone Stand",
        price: 9.99,
        product: true,
        service: false,
        searchtags: "smartphone stand, accessories, tech, product",
        description: "This is a description for Smartphone Stand. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-14.jpg",
      },
      {
        id: 17,
        company: "Gizmo Tech",
        title: "PC Hardware Upgrade",
        price: 89.99,
        product: false,
        service: true,
        searchtags: "PC hardware, upgrade, computer, tech, service",
        description: "This is a description for PC Hardware Upgrade. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-15.jpg",
      },
      {
        id: 18,
        company: "Gizmo Tech",
        title: "Wireless Keyboard and Mouse Combo",
        price: 39.99,
        product: true,
        service: false,
        searchtags: "keyboard, mouse, combo, tech, product",
        description: "This is a description for Wireless Keyboard and Mouse Combo. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-16.jpg",
      },
      {
        id: 19,
        company: "Mobile Solutions",
        title: "Screen Protector (iPhone)",
        price: 4.99,
        product: true,
        service: false,
        searchtags: "screen protector, iPhone, accessories, tech, product",
        description: "This is a description for iPhone Screen Protector. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-16.jpg",
      },
      {
        id: 20,
        company: "Mobile Solutions",
        title: "Phone Case (Samsung Galaxy)",
        price: 12.99,
        product: true,
        service: false,
        searchtags: "phone case, Samsung Galaxy, accessories, tech, product",
        description: "This is a description for Samsung Galaxy Phone Case. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-17.jpg",
      },
      {
        id: 21,
        company: "Tech Innovators",
        title: "Computer Virus Protection Software",
        price: 29.99,
        product: true,
        service: false,
        searchtags: "virus protection, software, tech, product",
        description: "This is a description for Virus Protection Software. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-18.jpg",
      },
      {
        id: 22,
        company: "Tech Innovators",
        title: "Printer Repair Service",
        price: 49.99,
        product: false,
        service: true,
        searchtags: "printer, repair, tech, service",
        description: "This is a description for Printer Repair Service. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-19.jpg",
      },
      {
        id: 23,
        company: "Electronics Emporium",
        title: "Cable Management Kit",
        price: 9.99,
        product: true,
        service: false,
        searchtags: "cable management, accessories, tech, product",
        description: "This is a description for Cable Management Kit. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-20.jpg",
      },
      {
        id: 24,
        company: "Electronics Emporium",
        title: "Smart Home Installation Service",
        price: 99.99,
        product: false,
        service: true,
        searchtags: "smart home, installation, tech, service",
        description: "This is a description for Smart Home Installation Service. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-21.jpg",
      },
      {
        id: 25,
        company: "Gadget Geeks",
        title: "Wireless Router (AC1200)",
        price: 39.99,
        product: true,
        service: false,
        searchtags: "wireless router, networking, tech, product",
        description: "This is a description for AC1200 Wireless Router. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-22.jpg",
      },
      {
        id: 26,
        company: "Gadget Geeks",
        title: "Tech Support Subscription (1 Year)",
        price: 79.99,
        product: false,
        service: true,
        searchtags: "tech support, subscription, tech, service",
        description: "This is a description for 1 Year Tech Support Subscription. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-23.jpg",
      },
      {
        id: 27,
        company: "Digital Delight",
        title: "Wireless Charging Pad",
        price: 19.99,
        product: true,
        service: false,
        searchtags: "wireless charging pad, charging, tech, product",
        description: "This is a description for Wireless Charging Pad. Lorem ipsum...",
        image: "https://placeholder-url.com/placeholder-image-24.jpg",
      },
    ];
    export default Posts;